version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: nus_user
      POSTGRES_PASSWORD: nus_password
      POSTGRES_DB: nus_tour
    ports:
      - "5432:5432"
